export const payload_bank_account_examples = [
  {
    name: 'ANZ',
    currency: 'IDR',
    icon: 'anz.svg',
    color: '#FFFFFF',
    bg_color: '#003D5E',
  },
  {
    name: 'BCA',
    currency: 'IDR',
    icon: 'bca.svg',
    color: '#FFFFFF',
    bg_color: '#0060AF',
  },
  {
    name: 'BJB',
    currency: 'IDR',
    icon: 'bjb.svg',
    color: '#165781',
    bg_color: '#F5F7F9',
  },
  {
    name: 'BNI',
    currency: 'IDR',
    icon: 'bni.svg',
    color: '#005B6A',
    bg_color: '#FFFFFF',
  },
  {
    name: 'BRI',
    currency: 'IDR',
    icon: 'bri.svg',
    color: '#FFFFFF',
    bg_color: '#00529C',
  },
  {
    name: 'BSI',
    currency: 'IDR',
    icon: 'bsi.svg',
    color: '#0CA49D',
    bg_color: '#FFFFFF',
  },
  {
    name: 'BTN',
    currency: 'IDR',
    icon: 'btn.svg',
    color: '#0069AC',
    bg_color: '#FEF200',
  },
  {
    name: 'BUKOPIN',
    currency: 'IDR',
    icon: 'bukopin.svg',
    color: '#0089CF',
    bg_color: '#FFFFFF',
  },
  {
    name: 'CIMB',
    currency: 'IDR',
    icon: 'cimb.svg',
    color: '#FFFFFF',
    bg_color: '#ED3124',
  },
  {
    name: 'CITI',
    currency: 'IDR',
    icon: 'citi.svg',
    color: '#FFFFFF',
    bg_color: '#2E68C4',
  },
  {
    name: 'DANAMON',
    currency: 'IDR',
    icon: 'danamon.svg',
    color: '#004F38',
    bg_color: '#FFFFFF',
  },
  {
    name: 'DIGIBANK',
    currency: 'IDR',
    icon: 'digibank.svg',
    color: '#1D1D1B',
    bg_color: '#FFC134',
  },
  {
    name: 'HSBC',
    currency: 'IDR',
    icon: 'hsbc.svg',
    color: '#231F20',
    bg_color: '#FFFFFF',
  },
  {
    name: 'JAGO',
    currency: 'IDR',
    icon: 'jago.svg',
    color: '#FDAF27',
    bg_color: '#FFFFFF',
  },
  {
    name: 'JENIUS',
    currency: 'IDR',
    icon: 'jenius.svg',
    color: '#FFFFFF',
    bg_color: '#05B0EE',
  },
  {
    name: 'MANDIRI',
    currency: 'IDR',
    icon: 'mandiri.svg',
    color: '#FFFFFF',
    bg_color: '#003D79',
  },
  {
    name: 'MAYBANK',
    currency: 'IDR',
    icon: 'maybank.svg',
    color: '#231F20',
    bg_color: '#FFCE4C',
  },
  {
    name: 'MEGA',
    currency: 'IDR',
    icon: 'mega.svg',
    color: '#595A59',
    bg_color: '#FFFFFF',
  },
  {
    name: 'OCBC',
    currency: 'IDR',
    icon: 'ocbc.svg',
    color: '#FFFFFF',
    bg_color: '#EC1F30',
  },
  {
    name: 'PANIN',
    currency: 'IDR',
    icon: 'panin.svg',
    color: '#2A4095',
    bg_color: '#FFFFFF',
  },
  {
    name: 'PERMATA',
    currency: 'IDR',
    icon: 'permata.svg',
    color: '#000000',
    bg_color: '#FFFFFF',
  },
  {
    name: 'UOB',
    currency: 'IDR',
    icon: 'uob.svg',
    color: '#FFFFFF',
    bg_color: '#123274',
  },
];
