export const payload_ewallet_account_examples = [
  {
    name: 'APPLEPAY',
    currency: 'IDR',
    icon: 'applepay.svg',
    color: '#000000',
    bg_color: '#FFFFFF',
  },
  {
    name: 'BLUEPAY',
    currency: 'IDR',
    icon: 'bluepay.svg',
    color: '#2093FD',
    bg_color: '#FFFFFF',
  },
  {
    name: 'CASHBAC',
    currency: 'IDR',
    icon: 'cashbac.svg',
    color: '#26ACE3',
    bg_color: '#FFFFFF',
  },
  {
    name: 'CASHLEZ',
    currency: 'IDR',
    icon: 'cashlez.svg',
    color: '#160F42',
    bg_color: '#FFFFFF',
  },
  {
    name: 'DANA',
    currency: 'IDR',
    icon: 'dana.svg',
    color: '#FFFFFF',
    bg_color: '#108EE9',
  },
  {
    name: 'FLIP',
    currency: 'IDR',
    icon: 'flip.svg',
    color: '#FFFFFF',
    bg_color: '#FD6542',
  },
  {
    name: 'GOPAY',
    currency: 'IDR',
    icon: 'gopay.svg',
    color: '#01ACD7',
    bg_color: '#FFFFFF',
  },
  {
    name: 'GPAY',
    currency: 'IDR',
    icon: 'gpay.svg',
    color: '#5F6368',
    bg_color: '#FFFFFF',
  },
  {
    name: 'KUDO',
    currency: 'IDR',
    icon: 'kudo.svg',
    color: '#FFFFFF',
    bg_color: '#0881D0',
  },
  {
    name: 'LINKAJA',
    currency: 'IDR',
    icon: 'linkaja.svg',
    color: '#FFFFFF',
    bg_color: '#E82529',
  },
  {
    name: 'OVO',
    currency: 'IDR',
    icon: 'ovo.svg',
    color: '#FFFFFF',
    bg_color: '#4C3494',
  },
  {
    name: 'PAYFAZZ',
    currency: 'IDR',
    icon: 'payfazz.svg',
    color: '#3A8FF3',
    bg_color: '#FFFFFF',
  },
  {
    name: 'PAYPALL',
    currency: 'IDR',
    icon: 'paypall.svg',
    color: '#1B2E7F',
    bg_color: '#FFFFFF',
  },
  {
    name: 'PAYPRO',
    currency: 'IDR',
    icon: 'paypro.svg',
    color: '#FFFFFF',
    bg_color: '#8A2784',
  },
  {
    name: 'SHOOPEEPAY',
    currency: 'IDR',
    icon: 'shoopeepay.svg',
    color: '#FFFFFF',
    bg_color: '#F0592C',
  },
  {
    name: 'UANGKU',
    currency: 'IDR',
    icon: 'uangku.svg',
    color: '#FFFFFF',
    bg_color: '#3BB8EA',
  },
];
